import type { BlogLanguage } from "../blog/types";

const journeyEn = {
  hero: {
    label: "From Software Engineering and AI to Product & Technology Leadership",
    title: "From Signal to System",
    body: "I started by teaching machines to understand Arabic text. Over time, the same discipline became a way to build products, teams, and operating systems that make intelligent automation reliable.",
    proofCta: "View proof of work",
    thinkingCta: "Read my thinking",
  },
  labels: {
    thesis: "Thesis",
    chapters: "The journey",
    turningPoints: "Turning points",
    proof: "Proof of work",
    method: "How I work",
    horizon: "Direction",
    journal: "Journal",
    current: "Current",
    capabilities: "Capabilities",
    tension: "Tension",
    decision: "Decision",
    newCapability: "New capability",
    impact: "Impact",
  },
  thesis: {
    title: "A career built around finding structure",
    body: "At first, the signal was language: Arabic text, social data, and machine learning models. Later, the signal became customer needs, engineering constraints, delivery gaps, and organizational ambiguity. The work changed, but the pattern stayed the same: find structure, make it usable, and build the system around it.",
    progressionLabel: "Career progression from signal to system",
    progression: [
      { title: "Signal", body: "Finding structure in language and data" },
      { title: "Layer", body: "Connecting technical capability to product value" },
      { title: "Machine", body: "Building repeatable delivery and quality loops" },
      { title: "System", body: "Leading product, engineering, quality, and AI as one whole" },
    ],
  },
  chaptersTitle: "Four chapters. One evolving way of thinking.",
  chapters: [
    {
      eyebrow: "Chapter 01 - Signal",
      title: "Reading the signal",
      time: "2013 - 2021 · Damascus · Academic AI/NLP foundation + early ML/NLP engineering",
      context: ["Academic foundation", "Early ML/NLP engineering"],
      body: [
        "This chapter began with an academic foundation in computer science, AI, and NLP, then continued into early ML/NLP engineering work on Arabic language and social data. The work included relation extraction, sentiment and emotion analysis, semantic structure, and machine learning models for non-standard Arabic text.",
        "The technical discipline was AI and NLP. The deeper habit was learning how to find structure inside noise.",
      ],
      tags: ["AI", "NLP", "Machine Learning", "Arabic Language Technology", "Software Engineering"],
      motif: ["Arabic text", "Social data", "NLP model", "Meaning"],
    },
    {
      eyebrow: "Chapter 02 - Layer",
      title: "Building the missing layer",
      time: "2020 - 2023 · Darmstadt",
      body: [
        "At L-One, I moved from models into product-like engineering: simulation, robotics, 3D visualization, conversational AI, and complex software built for real users. I learned that a working prototype is not enough. The missing layer is often the bridge between technical capability and usable product.",
        "When I later joined Wianco, that missing layer became explicit: product structure, customer understanding, backlog discipline, and translation between what the market needed and what engineering could build.",
      ],
      tags: ["Product Engineering", "Robotics Simulation", "Conversational AI", "Enterprise Software"],
      motif: ["User need", "Prototype", "Engineering", "Product layer"],
    },
    {
      eyebrow: "Chapter 03 - Machine",
      title: "Designing the machine that builds the machine",
      time: "2023 - 2025 · Darmstadt",
      body: [
        "Once the product layer was in place, the next constraint was the engineering system itself. The work shifted toward operating models, sprint discipline, code standards, quality workflows, and delivery accountability.",
        "This was also the phase where AI became more than a product feature. I introduced AI-assisted development practices, agentic workflows, structured project contexts, and review patterns that helped teams work with more clarity and evidence.",
      ],
      tags: ["Engineering Leadership", "QA", "Agentic SDLC", "Delivery Systems", "AI-assisted Development"],
      motif: ["Backlog", "Development", "QA", "Release", "Feedback"],
    },
    {
      eyebrow: "Chapter 04 - System",
      title: "Leading Product & Technology as one operating system",
      time: "2026 - Present · Wianco OTT Robotics GmbH",
      body: [
        "Today, the work brings the previous chapters together. I lead across Product Ownership, Software Development, and Quality Assurance - connecting roadmap, architecture, implementation, testing, release, and real-world operation.",
        "The role is no longer about building one thing. It is about building and running the system that makes reliable intelligent automation possible.",
      ],
      tags: ["Product & Technology Leadership", "Cross-functional Leadership", "AI Governance", "Intelligent Automation", "Operating Systems"],
      motif: ["Product", "Development", "Quality", "AI", "Release", "Customer value"],
      current: true,
    },
  ],
  turningPointsTitle: "The shifts that changed the work",
  turningPoints: [
    {
      title: "From models to meaning",
      challenge: "AI models could classify language, but the real question was whether the output helped someone make a better decision.",
      decision: "Move closer to the product and the user problem.",
      result: "Technical depth became connected to product judgment.",
    },
    {
      title: "From product to operating model",
      challenge: "Good ideas were not enough when ownership, quality, and delivery systems were unclear.",
      decision: "Build the missing structure around the product, not only the product itself.",
      result: "Product management, engineering discipline, and quality practices became one connected system.",
    },
    {
      title: "From AI feature to AI discipline",
      challenge: "AI can accelerate teams, but without boundaries it creates noise, risk, and false confidence.",
      decision: "Treat AI as an engineering discipline with governance, review, context, and evidence.",
      result: "Agentic workflows became useful because they were structured, not because they were magical.",
    },
  ],
  proofTitle: "Evidence, not adjectives",
  proofIntro: "Selected systems, functions, and practices built to make product and technology work more reliable.",
  proof: [
    { type: "Function", title: "Product Management Function", description: "Built product structure inside an engineering-led company where the function did not previously exist.", impact: "Created clearer translation between customer needs, priorities, backlog decisions, and engineering execution.", tags: ["Product", "Ownership", "Backlog"] },
    { type: "Platform", title: "AI-enabled platform capability", description: "Product and technical direction for an AI-enabled platform capability within the EMMA ecosystem.", impact: "Connected AI capability with enterprise needs such as governance, security, deployment, and operability.", tags: ["AI Platform", "Product Direction", "Enterprise"] },
    { type: "AI Capability", title: "ML-powered automation capability", description: "An early AI-powered automation capability within the EMMA ecosystem, shaped into a clear and usable product experience.", impact: "Moved machine learning from concept into practical automation with understandable behavior and user control.", tags: ["AI", "ML", "Automation"] },
    { type: "Operating Model", title: "QA Framework Before QA Existed", description: "Designed quality workflows and standards before a dedicated QA team was fully in place.", impact: "Created a ready structure that could be adopted when the team grew.", tags: ["QA", "Quality", "Release"] },
    { type: "Engineering Practice", title: "Agentic Development Workflow", description: "Introduced structured AI-assisted coding, review, project context, and edge-case thinking across development work.", impact: "Helped teams use AI with clearer boundaries, better review discipline, and more observable evidence.", tags: ["Agentic SDLC", "Code Review", "AI"] },
    { type: "Governance", title: "Release and Delivery Accountability", description: "Strengthened the connection between planning, implementation, testing, release readiness, and operational feedback.", impact: "Reduced ambiguity around ownership and made delivery more traceable.", tags: ["Release", "Delivery", "Accountability"] },
  ],
  method: {
    title: "How I work",
    subtitle: "Five lessons I learned by building systems, not just software.",
    loopLabel: "Practical operating loop",
    loop: ["Clarify", "Decide", "Build", "Verify", "Follow up"],
    principles: [
      { title: "Clarity before motion", body: "I define the decision, scope, and standard of completion before execution begins. Ambiguity costs more than the time it takes to remove it." },
      { title: "The missing layer is usually organizational", body: "Many recurring technical problems are process problems. Many process problems are ownership problems. I work backwards from the symptom to find what is structurally absent." },
      { title: "Build for the team that does not exist yet", body: "A system should not only serve the current structure. It should prepare the organization for the next level of scale, ownership, and quality." },
      { title: "AI as engineering discipline, not magic", body: "AI becomes useful inside serious software work only when it has boundaries, context, review, and observable evidence." },
      { title: "Close the loop", body: "Every commitment needs an owner, an action, and a follow-up. This small habit compounds into trust, predictability, and delivery quality." },
    ],
  },
  horizon: {
    title: "Where this is going",
    body: [
      "The current chapter is about consolidation: raising engineering ownership, clarifying product direction, strengthening quality and release discipline, and embedding AI into the development lifecycle in ways that improve reliability - not just speed.",
      "The longer horizon is senior product and technology leadership at larger scale: connecting technical depth, AI fluency, organizational design, and enterprise execution into one operating model.",
    ],
    linkedInCta: "Connect on LinkedIn",
    systemLabel: "Four tracks converging into one operating system",
    tracks: ["Product Direction", "Engineering System", "Quality & Release", "Governed AI"],
    system: "Reliable intelligent automation",
  },
  journal: {
    title: "Thinking in public",
    body: "Notes on product leadership, software engineering, AI, automation, and the operating systems behind reliable teams.",
    cta: "View journal",
  },
} as const;

const journeyAr = {
  ...journeyEn,
  hero: {
    label: "من هندسة البرمجيات والذكاء الاصطناعي إلى قيادة المنتج والتقنية",
    title: "من الإشارة إلى النظام",
    body: "بدأت بتعليم الآلات فهم النص العربي. ومع الوقت، تحولت المنهجية نفسها إلى طريقة لبناء المنتجات والفرق وأنظمة العمل التي تجعل الأتمتة الذكية موثوقة.",
    proofCta: "اطّلع على نماذج من العمل",
    thinkingCta: "اقرأ أفكاري",
  },
  labels: {
    thesis: "الفكرة",
    chapters: "الرحلة",
    turningPoints: "نقاط التحول",
    proof: "نماذج من العمل",
    method: "كيف أعمل",
    horizon: "الاتجاه",
    journal: "المدونة",
    current: "الفصل الحالي",
    capabilities: "مجالات الخبرة",
    tension: "التوتر",
    decision: "القرار",
    newCapability: "القدرة الجديدة",
    impact: "الأثر",
  },
  thesis: {
    title: "مسار مهني يقوم على اكتشاف البنية",
    body: "في البداية كانت الإشارة هي اللغة: النص العربي، والبيانات الاجتماعية، ونماذج تعلم الآلة. لاحقاً أصبحت الإشارة احتياجات العملاء، والقيود الهندسية، وفجوات التسليم، والغموض التنظيمي. تغيّر العمل، لكن النمط بقي واحداً: اكتشاف البنية، وجعلها قابلة للاستخدام، ثم بناء النظام المحيط بها.",
    progressionLabel: "تطور المسار من الإشارة إلى النظام",
    progression: [
      { title: "إشارة", body: "اكتشاف البنية في اللغة والبيانات" },
      { title: "طبقة", body: "ربط القدرة التقنية بقيمة المنتج" },
      { title: "آلة", body: "بناء حلقات متكررة للتسليم والجودة" },
      { title: "نظام", body: "قيادة المنتج والهندسة والجودة وAI ككل واحد" },
    ],
  },
  chaptersTitle: "أربعة فصول. وطريقة تفكير واحدة تتطور.",
  chapters: [
    { ...journeyEn.chapters[0], eyebrow: "الفصل 01 - الإشارة", title: "قراءة الإشارة", time: "2013 - 2021 · دمشق · أساس أكاديمي في AI/NLP + عمل هندسي مبكر في ML/NLP", context: ["أساس أكاديمي", "عمل هندسي مبكر في ML/NLP"], body: ["بدأ هذا الفصل بأساس أكاديمي في علوم الحاسوب والذكاء الاصطناعي ومعالجة اللغة الطبيعية، ثم استمر إلى عمل هندسي مبكر في ML/NLP على اللغة العربية والبيانات الاجتماعية. شمل العمل استخراج العلاقات، وتحليل المشاعر والعواطف، والبنية الدلالية، ونماذج تعلم الآلة للنص العربي غير المعياري.", "كان الانضباط التقني هو AI وNLP. أما العادة الأعمق فكانت تعلم اكتشاف البنية داخل الضجيج."], motif: ["نص عربي", "بيانات اجتماعية", "نموذج NLP", "معنى"] },
    { ...journeyEn.chapters[1], eyebrow: "الفصل 02 - الطبقة", title: "بناء الطبقة المفقودة", time: "2020 - 2023 · دارمشتات", body: ["في L-One انتقلت من النماذج إلى هندسة أقرب إلى المنتج: المحاكاة، والروبوتات، والتصور ثلاثي الأبعاد، والذكاء الاصطناعي الحواري، وبرمجيات معقدة لمستخدمين حقيقيين. تعلمت أن النموذج الأولي العامل لا يكفي؛ فالطبقة المفقودة غالباً هي الجسر بين القدرة التقنية والمنتج القابل للاستخدام.", "وعندما انضممت لاحقاً إلى Wianco، أصبحت هذه الطبقة واضحة: هيكلة المنتج، وفهم العميل، وانضباط قائمة العمل، والترجمة بين ما يحتاجه السوق وما تستطيع الهندسة بناءه."], motif: ["حاجة المستخدم", "نموذج أولي", "هندسة", "طبقة المنتج"] },
    { ...journeyEn.chapters[2], eyebrow: "الفصل 03 - الآلة", title: "تصميم الآلة التي تبني الآلة", time: "2023 - 2025 · دارمشتات", body: ["بعد بناء طبقة المنتج، أصبح القيد التالي هو النظام الهندسي نفسه. انتقل العمل إلى نماذج التشغيل، وانضباط دورات التطوير، ومعايير الشيفرة، ومسارات الجودة، والمساءلة عن التسليم.", "في هذه المرحلة أيضاً أصبح الذكاء الاصطناعي أكثر من ميزة في المنتج. أدخلت ممارسات تطوير مدعومة بالذكاء الاصطناعي، ومسارات عمل وكيلة، وسياقات منظمة للمشاريع، وأنماط مراجعة تساعد الفرق على العمل بوضوح وأدلة أفضل."], motif: ["قائمة العمل", "التطوير", "QA", "الإصدار", "التغذية الراجعة"] },
    { ...journeyEn.chapters[3], eyebrow: "الفصل 04 - النظام", title: "قيادة المنتج والتقنية كنظام تشغيل واحد", time: "2026 - الآن · Wianco OTT Robotics GmbH", body: ["اليوم يجمع العمل الفصول السابقة معاً. أقود عبر ملكية المنتج، وتطوير البرمجيات، وضمان الجودة، رابطاً خارطة الطريق بالمعمارية والتنفيذ والاختبار والإصدار والتشغيل الفعلي.", "لم يعد الدور متعلقاً ببناء شيء واحد، بل ببناء وتشغيل النظام الذي يجعل الأتمتة الذكية الموثوقة ممكنة."], motif: ["المنتج", "التطوير", "الجودة", "AI", "الإصدار", "قيمة العميل"], current: true },
  ],
  turningPointsTitle: "التحولات التي غيّرت طبيعة العمل",
  turningPoints: [
    { title: "من النماذج إلى المعنى", challenge: "استطاعت نماذج الذكاء الاصطناعي تصنيف اللغة، لكن السؤال الحقيقي كان: هل تساعد النتيجة شخصاً على اتخاذ قرار أفضل؟", decision: "الاقتراب أكثر من المنتج ومشكلة المستخدم.", result: "ارتبط العمق التقني بالحكم على المنتج." },
    { title: "من المنتج إلى نموذج التشغيل", challenge: "لم تكن الأفكار الجيدة كافية عندما كانت الملكية والجودة وأنظمة التسليم غير واضحة.", decision: "بناء الهيكل المفقود حول المنتج، لا المنتج وحده.", result: "أصبحت إدارة المنتج والانضباط الهندسي وممارسات الجودة نظاماً مترابطاً." },
    { title: "من ميزة AI إلى انضباط هندسي", challenge: "يمكن للذكاء الاصطناعي تسريع الفرق، لكنه من دون حدود يخلق ضجيجاً ومخاطر وثقة زائفة.", decision: "التعامل مع AI كانضباط هندسي له حوكمة ومراجعة وسياق وأدلة.", result: "أصبحت مسارات العمل الوكيلة مفيدة لأنها منظمة، لا لأنها سحرية." },
  ],
  proofTitle: "أدلة، لا صفات",
  proofIntro: "نماذج مختارة من الأنظمة والوظائف والممارسات التي بُنيت لجعل عمل المنتج والتقنية أكثر موثوقية.",
  proof: [
    { type: "وظيفة", title: "تأسيس وظيفة إدارة المنتج", description: "بنيت هيكل المنتج داخل شركة تقودها الهندسة ولم تكن هذه الوظيفة موجودة فيها من قبل.", impact: "أنشأ ذلك ترجمة أوضح بين احتياجات العملاء والأولويات وقرارات قائمة العمل والتنفيذ الهندسي.", tags: ["المنتج", "الملكية", "قائمة العمل"] },
    { type: "منصة", title: "قدرة منصة مدعومة بالذكاء الاصطناعي", description: "قدت اتجاه المنتج والتقنية لقدرة منصة مدعومة بالذكاء الاصطناعي ضمن منظومة EMMA.", impact: "ربطت قدرات AI باحتياجات المؤسسات مثل الحوكمة والأمن والنشر وقابلية التشغيل.", tags: ["منصة AI", "اتجاه المنتج", "المؤسسات"] },
    { type: "قدرة AI", title: "قدرة أتمتة مدعومة بتعلم الآلة", description: "قدرة مبكرة للأتمتة المدعومة بالذكاء الاصطناعي ضمن منظومة EMMA، صيغت كتجربة منتج واضحة وقابلة للاستخدام.", impact: "نقلت تعلم الآلة من مفهوم إلى أتمتة عملية ذات سلوك مفهوم وتحكم واضح للمستخدم.", tags: ["AI", "ML", "الأتمتة"] },
    { type: "نموذج تشغيل", title: "إطار جودة قبل وجود فريق QA", description: "صممت مسارات ومعايير الجودة قبل اكتمال وجود فريق متخصص لضمان الجودة.", impact: "أنشأت بنية جاهزة للتبني عندما نما الفريق.", tags: ["QA", "الجودة", "الإصدار"] },
    { type: "ممارسة هندسية", title: "مسار تطوير وكيلي", description: "أدخلت البرمجة والمراجعة وسياق المشروع والتفكير في الحالات الطرفية ضمن استخدام منظم للذكاء الاصطناعي.", impact: "ساعد ذلك الفرق على استخدام AI بحدود أوضح وانضباط مراجعة أفضل وأدلة أكثر قابلية للملاحظة.", tags: ["Agentic SDLC", "مراجعة الشيفرة", "AI"] },
    { type: "حوكمة", title: "المساءلة عن الإصدار والتسليم", description: "قويت الصلة بين التخطيط والتنفيذ والاختبار وجاهزية الإصدار والتغذية الراجعة التشغيلية.", impact: "قللت الغموض حول الملكية وجعلت التسليم أكثر قابلية للتتبع.", tags: ["الإصدار", "التسليم", "المساءلة"] },
  ],
  method: {
    title: "كيف أعمل",
    subtitle: "خمسة دروس تعلمتها من بناء الأنظمة، لا البرمجيات وحدها.",
    loopLabel: "حلقة التشغيل العملية",
    loop: ["وضّح", "قرّر", "ابنِ", "تحقّق", "تابع"],
    principles: [
      { title: "الوضوح قبل الحركة", body: "أحدد القرار والنطاق ومعيار الإنجاز قبل بدء التنفيذ. تكلفة الغموض أكبر من الوقت اللازم لإزالته." },
      { title: "الطبقة المفقودة غالباً تنظيمية", body: "كثير من المشكلات التقنية المتكررة هي مشكلات عمليات، وكثير من مشكلات العمليات هي مشكلات ملكية. أعود من العَرَض لأجد ما ينقص البنية." },
      { title: "ابنِ للفريق الذي لم يوجد بعد", body: "لا ينبغي للنظام أن يخدم الهيكل الحالي فقط، بل أن يهيئ المؤسسة للمستوى التالي من التوسع والملكية والجودة." },
      { title: "AI انضباط هندسي، لا سحر", body: "يصبح AI مفيداً في العمل البرمجي الجاد عندما تكون له حدود وسياق ومراجعة وأدلة قابلة للملاحظة." },
      { title: "أغلق الحلقة", body: "كل التزام يحتاج إلى مالك وإجراء ومتابعة. هذه العادة الصغيرة تتراكم لتصنع الثقة والتوقع وجودة التسليم." },
    ],
  },
  horizon: {
    title: "إلى أين يتجه هذا المسار",
    body: ["يركز الفصل الحالي على التثبيت: رفع الملكية الهندسية، وتوضيح اتجاه المنتج، وتقوية انضباط الجودة والإصدار، ودمج AI في دورة التطوير بما يحسن الموثوقية، لا السرعة فقط.", "أما الأفق الأبعد فهو قيادة المنتج والتقنية على نطاق أكبر: جمع العمق التقني، والطلاقة في AI، والتصميم التنظيمي، والتنفيذ المؤسسي في نموذج تشغيل واحد."],
    linkedInCta: "تواصل عبر LinkedIn",
    systemLabel: "أربعة مسارات تلتقي في نظام تشغيل واحد",
    tracks: ["اتجاه المنتج", "النظام الهندسي", "الجودة والإصدار", "AI محكوم"],
    system: "أتمتة ذكية موثوقة",
  },
  journal: {
    title: "التفكير بصوت مسموع",
    body: "ملاحظات حول قيادة المنتج، وهندسة البرمجيات، والذكاء الاصطناعي، والأتمتة، وأنظمة التشغيل التي تقف خلف الفرق الموثوقة.",
    cta: "عرض المدونة",
  },
} as const;

export const getJourneyNarrative = (language: BlogLanguage) =>
  language === "ar" ? journeyAr : journeyEn;
