export const copyAr = {
  common: {
    skipToContent: "الانتقال إلى المحتوى",
    primaryNavigation: "التنقل الرئيسي",
    footerNavigation: "روابط التذييل",
    menu: "القائمة",
    openMenu: "فتح القائمة",
    closeMenu: "إغلاق القائمة",
    switchLanguage: "عرض الموقع باللغة الإنجليزية",
    switchLanguageShort: "EN",
    readLabel: "للقراءة",
    readPostCta: "اقرأ المقال ←",
    backToBlog: "→ العودة إلى المدونة",
    linkedInCta: "LinkedIn ↗",
    cvNavLabel: "CV",
    cvCta: "عرض السيرة المهنية",
    cvClose: "إغلاق السيرة المهنية",
    cvOpen: "فتح في نافذة جديدة",
    cvDownload: "تنزيل السيرة المهنية",
    cvMobileTitle: "السيرة المهنية جاهزة للعرض",
    cvMobileBody: "افتح الملف في عارض PDF على جهازك للحصول على أفضل تجربة.",
    cvMissingTitle: "ملف السيرة المهنية غير متاح حاليًا",
    cvMissingBody: "لم نتمكن من تحميل ملف PDF. يرجى المحاولة مرة أخرى لاحقًا.",
    cvChecking: "جارٍ تجهيز السيرة المهنية...",
  },
  home: {
    role: "Head of Product & Technology",
    title: "أقود Product & Technology لبناء أنظمة ذكية يقودها الإنسان.",
    lede: "أجمع Product & Technology وSoftware Engineering بخبرة عملية في AI لأحوّل التعقيد إلى أنظمة واضحة، قابلة للفحص، وموثوقة.",
    thoughtsCta: "استكشف أفكاري",
    journeyCta: "تعرّف إلى رحلتي",
    blogCta: "تصفح المدونة",
    showAllCta: "عرض الكل ←",
    beliefsIndex: "01 · المبادئ",
    beliefsTitle: "ما أؤمن به",
    beliefsSubtitle: "المبادئ التي توجّه قيادتي وبنائي وتقييمي للأنظمة الذكية.",
    beliefs: [
      "يجب أن تعزّز التقنية حكم الإنسان، لا أن تستبدله.",
      "تحوّل قيادة Product & Technology التعقيد إلى قرارات واضحة، وملكية محددة، وأنظمة تثق بها الفرق.",
      "تكتسب أنظمة AI الثقة بالدليل: أن تكون مفهومة، وقابلة للاختبار، وخاضعة للمساءلة.",
    ],
    thoughtsIndex: "02 · أفكار مختارة",
    thoughtsTitle: "أكتب عن أنظمة تعمل في الواقع، لا في العروض.",
    allThoughtsCta: "عرض كل الكتابات",
    futureEyebrow: "مبدأ لما هو قادم",
    futureLines: ["أفضل طريقة", "للتنبؤ بالمستقبل", "هي أن نصنعه."],
    proofIndex: "03 · الخبرة المهنية",
    proofTitle: "الخبرة التي تقف خلف الأفكار.",
    proof: [
      {
        title: "Head of Product & Technology",
        body: "أوحّد المنتج والهندسة والجودة والتسليم في نظام عمل واضح.",
      },
      {
        title: "AI Engineer",
        body: "خبرة أكاديمية وعملية في AI وNLP، تركّز على أنظمة قابلة للفحص.",
      },
      {
        title: "MSc in Big Data Systems",
        body: "أساس في البيانات وNLP وتقييم التقنية بعيدًا عن الضجيج.",
      },
    ],
    journeyIndex: "04 · الخبرة وراء الأفكار",
    journeyTitle: "من AI وNLP وSoftware Engineering إلى قيادة Product & Technology.",
    journeyBody: "المحطات والمبادئ التي شكّلت طريقتي في بناء الفرق والأنظمة واتخاذ القرار.",
  },
  blog: {
    eyebrow: "أفكار من واقع العمل",
    title: "المدونة",
    subtitle: "مقالات عملية عن Product & Technology وSoftware Engineering وAI والأتمتة.",
    archiveLabel: "أرشيف الكتابات",
    archiveTitle: "أفكار عملية من واقع العمل.",
    archiveHint: "اختر موضوعًا أو ابدأ بالأحدث.",
    allPosts: "كل المقالات",
    filterLabel: "تصنيف المقالات",
    empty: "لا توجد مقالات منشورة ضمن هذا المحور حاليًا.",
    discussionLabel: "تابع النقاش",
    discussionTitle: "هل تفتح الفكرة سؤالًا في عملك؟",
    discussionBody: "تابع النقاش والكتابات الجديدة على LinkedIn.",
  },
  journey: {
    eyebrow: "من Software Engineering وAI إلى قيادة Product & Technology",
    titlePrefix: "من AI وNLP إلى قيادة",
    titleHighlight: "Product & Technology",
    subtitle: "رحلة من AI وSoftware Engineering إلى قيادة فرق وأنظمة عمل تسلّم بوضوح وموثوقية.",
    themesTitle: "محاور عملي",
    principlesTitle: "كيف أعمل",
    proofTitle: "أثر عملي",
    timelineTitle: "المسار المهني",
    themesLabel: "محاور العمل",
    principlesLabel: "مبادئ العمل",
    proofLabel: "أثر مهني",
    timelineLabel: "محطات مختارة",
    writingLabel: "أفكار من الممارسة",
    timelineAriaLabel: "محطات المسار المهني",
    impactLabel: "الأثر",
    typeLabels: {
      education: "تعليم",
      role: "دور تقني",
      leadership: "قيادة",
      product: "منتج",
      ai: "AI",
    },
    fallbackOutcomes: {
      masters: ["AI", "NLP", "أنظمة بيانات"],
      "l-one": ["Software Engineering", "Robotics Simulation", "CAD"],
      "wianco-lead": ["قيادة هندسية", "Delivery Reliability", "ملكية واضحة"],
      "ai-direction": ["Product & Technology", "AI Governance", "Technical Strategy"],
    },
    principles: [
      {
        title: "الوضوح أولًا",
        body: "أحدد القرار والنطاق ومعيار الإنجاز قبل التنفيذ.",
      },
      {
        title: "القياس بدل الانطباع",
        body: "أحوّل الالتزامات إلى نتائج قابلة للفحص.",
      },
      {
        title: "إغلاق الحلقات",
        body: "أربط كل مراجعة بإجراء ومالك وموعد متابعة.",
      },
      {
        title: "حماية الفريق من الغموض",
        body: "أوضح الملكية بين المنتج والهندسة والجودة لتقليل إعادة العمل.",
      },
      {
        title: "التصميم للتفويض",
        body: "أبني عمليات يستطيع الفريق امتلاكها دون اعتماد دائم عليّ.",
      },
    ],
    proofStories: [
      {
        title: "متابعة داخل التنفيذ",
        body: "ربط كل التزام بمالك ومعيار فحص وموعد مراجعة.",
      },
      {
        title: "ملكية واضحة بين الفرق",
        body: "تعريف الملكية ومعايير الجاهزية لتسريع القرار وتقليل الاعتماد على الأفراد.",
      },
      {
        title: "AI محكوم وقابل للفحص",
        body: "إدخال AI كقدرة هندسية ذات AI Governance وحدود استخدام واضحة.",
      },
    ],
  },
  notFound: {
    title: "404",
    label: "تعذر العثور على الصفحة",
    subtitle: "الصفحة غير موجودة",
    backHomeCta: "العودة إلى الرئيسية",
  },
  navigation: {
    home: "الرئيسية",
    blog: "أفكاري",
    journey: "رحلتي",
  },
} as const;
