export const copyEn = {
  common: {
    skipToContent: "Skip to content",
    primaryNavigation: "Primary navigation",
    footerNavigation: "Footer navigation",
    menu: "Menu",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    switchLanguage: "View the website in Arabic",
    switchLanguageShort: "AR",
    readLabel: "read",
    readPostCta: "Read article →",
    backToBlog: "← Back to the journal",
    linkedInCta: "LinkedIn ↗",
    cvNavLabel: "CV",
    cvCta: "View professional CV",
    cvClose: "Close CV",
    cvOpen: "Open in a new window",
    cvDownload: "Download CV",
    cvMobileTitle: "Your CV is ready to view",
    cvMobileBody: "Open the file in your device's PDF viewer for the best experience.",
    cvMissingTitle: "The CV is currently unavailable",
    cvMissingBody: "The PDF could not be loaded. Please try again later.",
    cvChecking: "Preparing the CV...",
  },
  home: {
    role: "Head of Product & Technology",
    title: "I lead Product & Technology to build intelligent systems directed by people.",
    lede: "I bring product, engineering, and practical AI experience together to turn complexity into systems that are clear, testable, and trusted.",
    thoughtsCta: "Explore my thinking",
    journeyCta: "Discover my journey",
    blogCta: "Explore the journal",
    showAllCta: "View all →",
    beliefsIndex: "01 · Principles",
    beliefsTitle: "What I believe",
    beliefsSubtitle: "The principles that shape how I lead, build, and evaluate intelligent systems.",
    beliefs: [
      "Technology should strengthen human judgment, not replace it.",
      "Product and technology leadership turns complexity into clear decisions, explicit ownership, and systems teams can trust.",
      "AI systems earn trust through evidence: they must be understandable, testable, and accountable.",
    ],
    thoughtsIndex: "02 · Selected thinking",
    thoughtsTitle: "I write about systems that work in practice, not only in presentations.",
    allThoughtsCta: "View all writing",
    futureEyebrow: "A principle for what comes next",
    futureLines: ["The best way", "to predict the future", "is to create it."],
    proofIndex: "03 · Professional depth",
    proofTitle: "The experience behind the ideas.",
    proof: [
      {
        title: "Head of Product & Technology",
        body: "I align product, engineering, quality, and delivery around one clear operating system.",
      },
      {
        title: "AI Engineer",
        body: "Academic and practical experience in AI and NLP, with a focus on systems that can be examined and trusted.",
      },
      {
        title: "MSc in Big Data Systems",
        body: "A foundation in data, NLP, and evidence-led technology assessment beyond the hype.",
      },
    ],
    journeyIndex: "04 · Experience behind the thinking",
    journeyTitle: "From AI, NLP, and software engineering to Product & Technology leadership.",
    journeyBody: "The milestones and principles that shaped how I build teams, design systems, and make decisions.",
  },
  blog: {
    eyebrow: "Ideas grounded in real work",
    title: "Journal",
    subtitle: "Practical writing on Product & Technology, software engineering, AI, and automation.",
    archiveLabel: "Writing archive",
    archiveTitle: "Practical ideas from the work itself.",
    archiveHint: "Choose a topic or begin with the latest.",
    allPosts: "All articles",
    filterLabel: "Filter articles by topic",
    empty: "There are no published articles in this topic yet.",
    discussionLabel: "Continue the conversation",
    discussionTitle: "Does this idea open a useful question in your work?",
    discussionBody: "Follow the discussion and new writing on LinkedIn.",
  },
  journey: {
    eyebrow: "From software engineering and AI to Product & Technology leadership",
    titlePrefix: "From AI and NLP to",
    titleHighlight: "Product & Technology leadership",
    subtitle: "A journey from technical depth to leading teams and operating systems that deliver with clarity and reliability.",
    themesTitle: "Where I create value",
    principlesTitle: "How I work",
    proofTitle: "Professional impact",
    timelineTitle: "Career journey",
    themesLabel: "Areas of work",
    principlesLabel: "Working principles",
    proofLabel: "Professional impact",
    timelineLabel: "Selected milestones",
    writingLabel: "Ideas from practice",
    timelineAriaLabel: "Career journey milestones",
    impactLabel: "Impact",
    typeLabels: {
      education: "Education",
      role: "Technical role",
      leadership: "Leadership",
      product: "Product",
      ai: "AI",
    },
    fallbackOutcomes: {
      masters: ["AI", "NLP", "Data systems"],
      "l-one": ["Software Engineering", "Robotics Simulation", "CAD"],
      "wianco-lead": ["Engineering leadership", "Delivery Reliability", "Clear ownership"],
      "ai-direction": ["Product & Technology", "AI Governance", "Technical Strategy"],
    },
    principles: [
      {
        title: "Clarity before motion",
        body: "I define the decision, scope, and standard of completion before execution begins.",
      },
      {
        title: "Evidence over impression",
        body: "I turn commitments into outcomes that can be observed and examined.",
      },
      {
        title: "Close the loop",
        body: "Every review ends with an action, an owner, and a clear follow-up point.",
      },
      {
        title: "Protect teams from ambiguity",
        body: "I make ownership across product, engineering, and quality explicit to reduce rework.",
      },
      {
        title: "Design for delegation",
        body: "I build operating practices the team can own without depending on me.",
      },
    ],
    proofStories: [
      {
        title: "Accountability inside delivery",
        body: "Every commitment is tied to an owner, a verification standard, and a review date.",
      },
      {
        title: "Clear ownership across teams",
        body: "Explicit ownership and readiness criteria accelerate decisions and reduce dependence on individuals.",
      },
      {
        title: "Governed, testable AI",
        body: "AI is introduced as an engineering capability with clear governance, boundaries, and evidence.",
      },
    ],
  },
  notFound: {
    title: "404",
    label: "Page not found",
    subtitle: "This page does not exist.",
    backHomeCta: "Return home",
  },
  navigation: {
    home: "Home",
    blog: "Thinking",
    journey: "Journey",
  },
} as const;
